export const products = [
    {
        id: '1',
        name: 'SafeTrip Europe',
        category: 'Insurance',
        price: 85,
        description: 'Travel insurance covering medical and cancellation costs in Europe.',
    },
    {
        id: '9',
        name: 'SmartHome Protect',
        category: 'Insurance',
        price: 120,
        description: 'Full-coverage home insurance: fire, flooding, and natural disasters.',
    },
    {
        id: '10',
        name: 'Pet Health Premium',
        category: 'Insurance',
        price: 95,
        description: 'Your furry companions are family, and they deserve the best care without compromise.',
    },
    {
        id: '11',
        name: 'Student Essential Health & Living',
        category: 'Insurance',
        price: 60,
        description: 'Tailored specifically for the university lifestyle, providing essential student-focused protection.',
    },
    {
        id: '12',
        name: 'Casco Plus',
        category: 'Insurance',
        price: 245,
        description: 'Ultimate road freedom with zero-stress repair and recovery.',
    },
    {
        id: '13',
        name: 'Cyber-Safe Lite Protection',
        category: 'Insurance',
        price: 45,
        description: 'Shield your digital life with a simplified, instant-activation safety net.',
    },
    {
        id: '2',
        name: 'Flash Loan 10,000',
        category: 'Loans',
        price: 150, // Processing fee
        description: 'Instant personal loan with a one-time processing fee.',
    },
    {
        id: '3',
        name: 'Revo-Gold Account',
        category: 'Digital Banking',
        price: 55, // Per month
        description: 'Premium digital banking with exclusive perks. (Monthly fee)',
    },
    {
        id: '4',
        name: 'Starter Investment Portfolio',
        category: 'Investments',
        price: 200,
        description: 'A starter kit for secure investments and portfolio tracking.',
    },
    {
        id: '14',
        name: 'Dividend Aristocrats Portfolio',
        category: 'Investments',
        price: 200,
        description: 'Focus: Passive Income and Stability. Best for users looking for regular cash flow.',
    },
    {
        id: '15',
        name: 'The "Inflation Shield" Portfolio',
        category: 'Investments',
        price: 200,
        description: 'Focus: Protecting purchasing power. Best for conservative users worried about rising prices.',
    },
    {
        id: '16',
        name: 'Global Tech Giants Portfolio',
        category: 'Investments',
        price: 200,
        description: 'Focus: High Growth and Innovation. Best for high risk tolerance young investors.',
    },
    {
        id: '17',
        name: 'The "Recession-Proof" Defensive Portfolio',
        category: 'Investments',
        price: 200,
        description: 'Focus: Security and Low Volatility. Best for cautious investors during market crashes.',
    },
    {
        id: '5',
        name: 'Startup PRO Account',
        category: 'Business',
        price: 99,
        description: 'All-in-one financial toolkit for startups and SMEs.',
    },
    {
        id: '6',
        name: 'Cashback Plus Activation',
        category: 'Promotions',
        price: 0,
        description: 'Opt-in for 5% cashback on all supermarket purchases this month.',
    },
    {
        id: '7',
        name: 'Tax Optimizer Tool',
        category: 'Calculators',
        price: 25,
        description: 'Advanced calculator tool to project year-end business taxes.',
    },
    {
        id: '8',
        name: 'Real Estate Legal Bundle',
        category: 'Document Center',
        price: 150,
        description: 'Standardized templates and legal docs for real estate.',
    }
];
